### ISSUE TITLE
gcylc/gsummary: KeyError point_string

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1564]
![screenshot_keyerror_pointstring](https://cloud.githubusercontent.com/assets/1138333/9056923/3244396e-3a8e-11e5-87d8-5d31cc01deaf.png)

Error reported:
"opened cylc gsummary and this popped up when I clicked to open the" suite.

**Comment by benfitzpatrick** [comment]
![screenshot_removed_task_then_reloaded](https://cloud.githubusercontent.com/assets/1138333/9056158/e5eaa562-3a88-11e5-9afb-5c1060dc5686.png)

I got a similar error by having gcylc open in tree view showing all my tasks, removing a task from the suite.rc, and reloading.

**Comment by arjclark** [comment]
Encountered again as:

```
gcylc has a problem.

Traceback (most recent call last):
  File "path/to/cylc-6.4.1.u2/lib/cylc/gui/
updater_tree.py" line 402, in update_gui
  if "root" in new_fam_data[point_string]:
KeyError: '20150825T0900Z'
```
(I have a screenshot in an email but for whatever reason can't get that to move into here, screenshot it myself or copy it into any form of graphics package...)

**Comment by matthewrmshin** [comment]
Can we check that it is fixed on master or not, please?

**Comment by arjclark** [comment]
@matthewrmshin - the steps in the code that lead to the original error being thrown have not changed.

**Comment by arjclark** [comment]
Confirmed as still a problem in 6.6.1 with this error report:
```
Traceback (most recent call last):
  File ".../cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 2975, in check_filter_entry
    self.refresh_views()
  File ".../cylc-6.6.1/lib/cylc/gui/app_gcylc.py", line 2980, in refresh_views
    view.refresh()
  File ".../cylc-6.6.1/lib/cylc/gui/view_tree.py", line 243, in refresh
    self.t.update_gui()
  File ".../cylc-6.6.1/lib/cylc/gui/updater_tree.py", line 373, in update_gui
    families = list(self.ancestors[name])
KeyError: 'rose_ana_meto_xc40_hadgem_nd_30day_atmos_proc'
```
